import os
import json

ws = r"c:\Antigravity\yavrukusa-surpriz-main\yavrukusa-surpriz-main"
fotos_dir = os.path.join(ws, "fotoğraflar")
lovepoem_dir = os.path.join(ws, "lovepoem")
out_js_path = os.path.join(ws, "galeri-data.js")

ALBUM_NAMES = {
    "solohanım": "☀️ Solo Hanım",
    "us": "❤️‍🔥 US (Biz)"
}

PHOTO_EXTS = {".jpg", ".jpeg", ".png", ".webp", ".gif", ".heic", ".bmp"}
VIDEO_EXTS = {".mp4", ".webm", ".mov", ".avi", ".mkv"}

albumler = [
    {"id": "all", "title": "🌸 Tüm Fotoğraf & Videolar"}
]

medya_listesi = []
total_photos = 0
total_videos = 0

# 1. Scan fotoğraflar directory subfolders
if os.path.exists(fotos_dir):
    for item in sorted(os.listdir(fotos_dir)):
        # Skip hidden files
        if item.startswith("."):
            continue
            
        item_path = os.path.join(fotos_dir, item)
        if os.path.isdir(item_path):
            folder_key = item.lower().replace(" ", "_")
            cat_id = f"cat_{folder_key}"
            
            friendly_title = ALBUM_NAMES.get(item.lower(), f"✈️ {item}")
            albumler.append({"id": cat_id, "title": friendly_title})
            
            files = sorted(os.listdir(item_path))
            for f in files:
                if f.startswith("."):
                    continue
                ext = os.path.splitext(f)[1].lower()
                rel_path = f"fotoğraflar/{item}/{f}"
                clean_title = f"{friendly_title}"
                
                if ext in PHOTO_EXTS:
                    medya_listesi.append({
                        "type": "photo",
                        "category": cat_id,
                        "src": rel_path,
                        "title": clean_title
                    })
                    total_photos += 1
                elif ext in VIDEO_EXTS:
                    medya_listesi.append({
                        "type": "video",
                        "category": cat_id,
                        "src": rel_path,
                        "poster": "",
                        "title": clean_title
                    })
                    total_videos += 1

# 2. Scan lovepoem directory for videos
if os.path.exists(lovepoem_dir):
    cat_id = "cat_lovepoem"
    albumler.append({"id": cat_id, "title": "🪶 Lovepoem (Videolar)"})
    
    files = sorted(os.listdir(lovepoem_dir))
    for f in files:
        if f.startswith("."):
            continue
        ext = os.path.splitext(f)[1].lower()
        if ext in VIDEO_EXTS:
            poster_name = os.path.splitext(f)[0] + ".jpg"
            poster_path = f"lovepoem/{poster_name}" if os.path.exists(os.path.join(lovepoem_dir, poster_name)) else ""
            medya_listesi.append({
                "type": "video",
                "category": cat_id,
                "src": f"lovepoem/{f}",
                "poster": poster_path,
                "title": f"Lovepoem #{os.path.splitext(f)[0]}"
            })
            total_videos += 1

js_content = f"""// AUTO-GENERATED BY foto-tara.py
const albumler = {json.dumps(albumler, ensure_ascii=False, indent=2)};

const medyaListesi = {json.dumps(medya_listesi, ensure_ascii=False, indent=2)};
"""

with open(out_js_path, "w", encoding="utf-8") as out:
    out.write(js_content)

print(f"TARAMA TAMAMLANDI: Toplam {len(albumler)-1} Albüm, {total_photos} Fotoğraf, {total_videos} Video bulundu ve galeri güncellendi!")
