import os
import json

ws = r"c:\Antigravity\yavrukusa-surpriz-main\yavrukusa-surpriz-main"
fotos_dir = os.path.join(ws, "fotoğraflar")
out_js_path = os.path.join(ws, "galeri-data.js")

# Auto-convert iPhone HEIC files to standard web JPG
try:
    from PIL import Image
    import pillow_heif
    pillow_heif.register_heif_opener()
    
    for root, dirs, files in os.walk(fotos_dir):
        for f in files:
            ext = os.path.splitext(f)[1].lower()
            if ext in [".heic", ".heif"]:
                heic_path = os.path.join(root, f)
                jpg_name = os.path.splitext(f)[0] + ".jpg"
                jpg_path = os.path.join(root, jpg_name)
                try:
                    img = Image.open(heic_path)
                    img.save(jpg_path, "JPEG", quality=92)
                    os.remove(heic_path)
                    print(f"HEIC Dönüştürüldü: {f} -> {jpg_name}")
                except Exception as err:
                    print(f"HEIC dönüşüm hatası {f}: {err}")
except Exception as e:
    pass

ALBUM_NAMES = {
    "bestiii": "🌸 Bestiii",
    "solohanım": "☀️ Solo Hanım",
    "us": "❤️‍🔥 US"
}

PHOTO_EXTS = {".jpg", ".jpeg", ".png", ".webp", ".gif", ".bmp"}
VIDEO_EXTS = {".mp4", ".webm", ".mov", ".avi", ".mkv"}

albumler = [
    {"id": "cat_bestiii", "title": "🌸 Bestiii"}
]

medya_listesi = []
total_photos = 0
total_videos = 0

if os.path.exists(fotos_dir):
    folders = sorted(os.listdir(fotos_dir))
    for f in list(folders):
        if f.lower() == "bestiii":
            folders.remove(f)
            folders.insert(0, f)

    for item in folders:
        if item.startswith("."):
            continue
            
        item_path = os.path.join(fotos_dir, item)
        if os.path.isdir(item_path):
            folder_key = item.lower().replace(" ", "_")
            cat_id = f"cat_{folder_key}"
            
            friendly_title = ALBUM_NAMES.get(item.lower(), f"✈️ {item.capitalize()}")
            
            if not any(a["id"] == cat_id for a in albumler):
                albumler.append({"id": cat_id, "title": friendly_title})
            
            files = sorted(os.listdir(item_path))
            for f in files:
                if f.startswith("."):
                    continue
                ext = os.path.splitext(f)[1].lower()
                rel_path = f"fotoğraflar/{item}/{f}"
                clean_title = f"{friendly_title}"
                
                if ext in PHOTO_EXTS:
                    medya_listesi.append({
                        "type": "photo",
                        "category": cat_id,
                        "src": rel_path,
                        "title": clean_title
                    })
                    total_photos += 1
                elif ext in VIDEO_EXTS:
                    medya_listesi.append({
                        "type": "video",
                        "category": cat_id,
                        "src": rel_path,
                        "poster": "",
                        "title": clean_title
                    })
                    total_videos += 1

js_content = f"""// AUTO-GENERATED BY foto-tara.py
const albumler = {json.dumps(albumler, ensure_ascii=False, indent=2)};

const medyaListesi = {json.dumps(medya_listesi, ensure_ascii=False, indent=2)};
"""

with open(out_js_path, "w", encoding="utf-8") as out:
    out.write(js_content)

print(f"TARAMA TAMAMLANDI: Toplam {len(albumler)} Albüm, {total_photos} Fotoğraf, {total_videos} Video bulundu!")
