// AUTO-GENERATED BY foto-tara.py
const albumler = [
  {
    "id": "all",
    "title": "🌸 Tüm Fotoğraf & Videolar"
  },
  {
    "id": "cat_solohanım",
    "title": "☀️ Solo Hanım"
  },
  {
    "id": "cat_us",
    "title": "❤️‍🔥 US (Biz)"
  },
  {
    "id": "cat_lovepoem",
    "title": "🪶 Lovepoem (Videolar)"
  }
];

const medyaListesi = [
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/1.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/10.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/11.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/12.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/13.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/14.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/15.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/2.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/3.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/4.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/6.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/7.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/8.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/9.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/1.jpg",
    "title": "❤️‍🔥 US (Biz)"
  },
  {
    "type": "video",
    "category": "cat_us",
    "src": "fotoğraflar/us/1.mp4",
    "poster": "",
    "title": "❤️‍🔥 US (Biz)"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/10.jpg",
    "title": "❤️‍🔥 US (Biz)"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/11.jpg",
    "title": "❤️‍🔥 US (Biz)"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/12.jpg",
    "title": "❤️‍🔥 US (Biz)"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/13.jpg",
    "title": "❤️‍🔥 US (Biz)"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/14.jpg",
    "title": "❤️‍🔥 US (Biz)"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/15.jpg",
    "title": "❤️‍🔥 US (Biz)"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/16.jpg",
    "title": "❤️‍🔥 US (Biz)"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/17.jpg",
    "title": "❤️‍🔥 US (Biz)"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/2.jpg",
    "title": "❤️‍🔥 US (Biz)"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/3.jpg",
    "title": "❤️‍🔥 US (Biz)"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/4.jpg",
    "title": "❤️‍🔥 US (Biz)"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/5.jpg",
    "title": "❤️‍🔥 US (Biz)"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/6.jpg",
    "title": "❤️‍🔥 US (Biz)"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/7.jpg",
    "title": "❤️‍🔥 US (Biz)"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/8.jpg",
    "title": "❤️‍🔥 US (Biz)"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/9.jpg",
    "title": "❤️‍🔥 US (Biz)"
  },
  {
    "type": "video",
    "category": "cat_lovepoem",
    "src": "lovepoem/1.mp4",
    "poster": "lovepoem/1.jpg",
    "title": "Lovepoem #1"
  },
  {
    "type": "video",
    "category": "cat_lovepoem",
    "src": "lovepoem/2.mp4",
    "poster": "",
    "title": "Lovepoem #2"
  },
  {
    "type": "video",
    "category": "cat_lovepoem",
    "src": "lovepoem/3.mp4",
    "poster": "",
    "title": "Lovepoem #3"
  },
  {
    "type": "video",
    "category": "cat_lovepoem",
    "src": "lovepoem/4.mp4",
    "poster": "lovepoem/4.jpg",
    "title": "Lovepoem #4"
  }
];
