// AUTO-GENERATED BY foto-tara.py
const albumler = [
  {
    "id": "cat_bestiii",
    "title": "🌸 Bestiii"
  },
  {
    "id": "cat_amasra",
    "title": "✈️ Amasra"
  },
  {
    "id": "cat_solohanım",
    "title": "☀️ Solo Hanım"
  },
  {
    "id": "cat_us",
    "title": "❤️‍🔥 US"
  }
];

const medyaListesi = [
  {
    "type": "photo",
    "category": "cat_amasra",
    "src": "fotoğraflar/amasra/IMG_1885.jpg",
    "title": "✈️ Amasra"
  },
  {
    "type": "photo",
    "category": "cat_amasra",
    "src": "fotoğraflar/amasra/IMG_1887.jpg",
    "title": "✈️ Amasra"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/1.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/10.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/11.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/12.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/13.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/14.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/15.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/2.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/3.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/4.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/6.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/7.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/8.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_solohanım",
    "src": "fotoğraflar/solohanım/9.jpg",
    "title": "☀️ Solo Hanım"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/1.jpg",
    "title": "❤️‍🔥 US"
  },
  {
    "type": "video",
    "category": "cat_us",
    "src": "fotoğraflar/us/1.mp4",
    "poster": "",
    "title": "❤️‍🔥 US"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/10.jpg",
    "title": "❤️‍🔥 US"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/11.jpg",
    "title": "❤️‍🔥 US"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/12.jpg",
    "title": "❤️‍🔥 US"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/13.jpg",
    "title": "❤️‍🔥 US"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/14.jpg",
    "title": "❤️‍🔥 US"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/15.jpg",
    "title": "❤️‍🔥 US"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/16.jpg",
    "title": "❤️‍🔥 US"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/17.jpg",
    "title": "❤️‍🔥 US"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/2.jpg",
    "title": "❤️‍🔥 US"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/3.jpg",
    "title": "❤️‍🔥 US"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/4.jpg",
    "title": "❤️‍🔥 US"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/5.jpg",
    "title": "❤️‍🔥 US"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/6.jpg",
    "title": "❤️‍🔥 US"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/7.jpg",
    "title": "❤️‍🔥 US"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/8.jpg",
    "title": "❤️‍🔥 US"
  },
  {
    "type": "photo",
    "category": "cat_us",
    "src": "fotoğraflar/us/9.jpg",
    "title": "❤️‍🔥 US"
  }
];
